// AUTO-GENERATED by scripts/generate-song-library.mjs — DO NOT EDIT MANUALLY
// Generated from public/pianosongs/ metadata.json + file listing
// 25 songs

import type { SongLibraryEntry } from './song-library.types';

export const BUILT_IN_SONG_LIBRARY: ReadonlyArray<SongLibraryEntry> = [
  {
    id: "another-love",
    title: "Another love",
    artist: "Tom Odell",
    assetPath: "/pianosongs/Another love.mid",
    difficulty: "Intermedio",
    tags: ["melodico", "moderno", "romantico"],
  },

  {
    id: "ballade-pour-adeline",
    title: "Ballade pour adeline",
    artist: "Richard Clayderman",
    assetPath: "/pianosongs/Ballade pour adeline.mid",
    difficulty: "Intermedio",
    tags: ["melodico", "romantico", "popular"],
  },

  {
    id: "bohemian-rhapsody",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    assetPath: "/pianosongs/Bohemian Rhapsody.mid",
    difficulty: "Intermedio",
    tags: ["rock", "popular", "dinamica"],
  },

  {
    id: "canon-in-d-major",
    title: "Canon In D Major",
    artist: "Johann Pachelbel",
    assetPath: "/pianosongs/Canon In D Major.mid",
    difficulty: "Principiante",
    featured: true,
    tags: ["clasico", "melodico", "acompanamiento"],
  },

  {
    id: "clair-de-lune-easy-piano",
    title: "Clair de lune (Easy Piano)",
    artist: "Claude Debussy",
    assetPath: "/pianosongs/Clair de lune (Easy_Piano).mid",
    difficulty: "Principiante",
    tags: ["clasico", "melodico", "impresionismo"],
  },

  {
    id: "clair-delune-advanced",
    title: "Clair deLune (Advanced)",
    artist: "Claude Debussy",
    assetPath: "/pianosongs/Clair deLune (Advanced).mid",
    difficulty: "Avanzado",
    tags: ["clasico", "melodico", "impresionismo"],
  },

  {
    id: "fly-me-to-the-moon",
    title: "Fly Me to the Moon",
    artist: "Frank Sinatra",
    assetPath: "/pianosongs/Fly Me to the Moon.mid",
    difficulty: "Intermedio",
    tags: ["jazz", "popular", "swing"],
  },

  {
    id: "hallelujah",
    title: "Hallelujah",
    artist: "Leonard Cohen",
    assetPath: "/pianosongs/Hallelujah.mid",
    difficulty: "Principiante",
    featured: true,
    tags: ["balada", "acompanamiento", "popular"],
  },

  {
    id: "hungarian-dance-no-5",
    title: "Hungarian Dance No.5",
    artist: "Johannes Brahms",
    assetPath: "/pianosongs/Hungarian Dance No.5.mid",
    difficulty: "Avanzado",
    tags: ["clasico", "dinamica", "tecnica"],
  },

  {
    id: "in-the-hall-of-the-mountain-king",
    title: "In The Hall of The Mountain King",
    artist: "Edvard Grieg",
    assetPath: "/pianosongs/In The Hall of The Mountain King.mid",
    difficulty: "Intermedio",
    tags: ["clasico", "energia", "ritmo"],
  },

  {
    id: "la-campanella",
    title: "La Campanella",
    artist: "Franz Liszt",
    assetPath: "/pianosongs/La Campanella.mid",
    difficulty: "Avanzado",
    tags: ["virtuosismo", "saltos", "tecnica"],
  },

  {
    id: "married-life",
    title: "Married Life",
    artist: "Michael Giacchino",
    assetPath: "/pianosongs/Married Life.mid",
    difficulty: "Intermedio",
    tags: ["cine", "melodico", "romantico"],
  },

  {
    id: "moonlight-sonata",
    title: "Moonlight Sonata",
    artist: "Ludwig van Beethoven",
    assetPath: "/pianosongs/Moonlight Sonata.mid",
    difficulty: "Intermedio",
    tags: ["clasico", "melodico", "expresivo"],
  },

  {
    id: "nocturne-in-c-minor",
    title: "Nocturne In C# Minor",
    artist: "Frédéric Chopin",
    assetPath: "/pianosongs/Nocturne In C# Minor.mid",
    difficulty: "Avanzado",
    tags: ["clasico", "melodico", "expresivo"],
  },

  {
    id: "nocturne-op-9",
    title: "Nocturne Op 9",
    artist: "Frédéric Chopin",
    assetPath: "/pianosongs/Nocturne Op 9.mid",
    difficulty: "Intermedio",
    tags: ["clasico", "melodico", "romantico"],
  },

  {
    id: "nuvole-bianche",
    title: "Nuvole Bianche",
    artist: "Ludovico Einaudi",
    assetPath: "/pianosongs/Nuvole Bianche.mid",
    difficulty: "Intermedio",
    featured: true,
    tags: ["moderno", "melodico", "minimalismo"],
  },

  {
    id: "perfect",
    title: "Perfect",
    artist: "Ed Sheeran",
    assetPath: "/pianosongs/Perfect.mid",
    difficulty: "Principiante",
    tags: ["popular", "balada", "romantico"],
  },

  {
    id: "pirates-of-the-caribbean",
    title: "Pirates of the Caribbean",
    artist: "Klaus Badelt",
    assetPath: "/pianosongs/Pirates of the Caribbean.mid",
    difficulty: "Intermedio",
    tags: ["cine", "energia", "ritmo"],
  },

  {
    id: "river-flows-in-you",
    title: "River Flows In You",
    artist: "Yiruma",
    assetPath: "/pianosongs/River Flows In You.mid",
    difficulty: "Intermedio",
    featured: true,
    tags: ["melodico", "moderno", "romantico"],
  },

  {
    id: "rondo-alla-turca",
    title: "Rondo Alla Turca",
    artist: "W. A. Mozart",
    assetPath: "/pianosongs/Rondo Alla Turca.mid",
    difficulty: "Avanzado",
    tags: ["clasico", "velocidad", "articulacion"],
  },

  {
    id: "rush-e-original",
    title: "Rush E Original",
    artist: "Sheet Music Boss",
    assetPath: "/pianosongs/Rush E Original.mid",
    difficulty: "Avanzado",
    tags: ["reto", "denso", "rapido"],
  },

  {
    id: "sonate-no-14-moonlight-3rd-movement",
    title: "Sonate No 14 “Moonlight” 3rd Movement",
    artist: "Ludwig van Beethoven",
    assetPath: "/pianosongs/Sonate No 14 “Moonlight” 3rd Movement.mid",
    difficulty: "Avanzado",
    tags: ["clasico", "velocidad", "virtuosismo"],
  },

  {
    id: "the-entertainer",
    title: "The Entertainer",
    artist: "Scott Joplin",
    assetPath: "/pianosongs/The Entertainer.mid",
    difficulty: "Intermedio",
    featured: true,
    tags: ["ragtime", "ritmo", "clasico"],
  },

  {
    id: "the-forsaken-waltz",
    title: "The Forsaken Waltz",
    artist: "Desconocido",
    assetPath: "/pianosongs/The Forsaken Waltz.mid",
    difficulty: "Intermedio",
    tags: ["vals", "melodico", "misterioso"],
  },

  {
    id: "waltz-of-the-flowers",
    title: "Waltz Of The Flowers",
    artist: "Pyotr Ilyich Tchaikovsky",
    assetPath: "/pianosongs/Waltz Of The Flowers.mid",
    difficulty: "Avanzado",
    tags: ["clasico", "vals", "orquestal"],
  },

] as const;
